behaviors:
  RacingBehaviour:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024            
      buffer_size: 10240          
      learning_rate: 0.0001       
      beta: 0.002                 
      epsilon: 0.2
      lambd: 0.97                 
      num_epoch: 4
    network_settings:
      normalize: true
      hidden_units: 512           
      num_layers: 3
      vis_encode_type: simple     
    reward_signals:
      extrinsic:
        gamma: 0.999              
        strength: 1.0
    max_steps: 100000000          
    time_horizon: 256             
    summary_freq: 50000

engine_settings:
  time_scale: 5